In [2]:
from faker import Faker
import pandas as pd
import numpy as np
import random
import datetime
import time

In [3]:
# Loading the data
recipe_ingredients_data = pd.read_csv('datasets/hca_recipe_ingredients.csv')

for column in recipe_ingredients_data.columns:
    print(column)

Id
recipe_id
food_item_id
carbohydrate
protein
energy
lipid_fat
quantity
unit
eqv
food_type
substitute_item_id
substitute_type

In [66]:
recipe_ingredients_data.head(20)

,Id,recipe_id,food_item_id,carbohydrate,protein,energy,lipid_fat,quantity,unit,eqv,food_type,substitute_item_id,substitute_type
0,1,29,6675,123.00,0.00,540,1.5,150,g,50.00,food_items,0,NaN
1,2,29,5126,0.00,0.00,0,0.0,100,g,0.25,food_items,0,NaN
2,3,29,24429,50.00,0.00,200,0.0,50,g,30.00,food_items,0,NaN
3,4,29,24089,26.35,4.05,111,0.0,150,g,148.00,food_items,0,NaN
4,18,84,238521,11.00,8.00,122,3.0,1,cup,244.00,food_items,0,NaN
5,19,84,239698,166.20,18.50,1153,27.7,240,g,240.00,food_items,0,NaN
6,20,84,239699,1.00,2.00,40,0.0,1,1 tbsp,7.00,food_items,0,NaN
7,21,84,239700,2.00,2.10,91,0.8,14,g,14.00,food_items,0,NaN
8,31,96,239507,14.40,86.60,1299,72.2,433,g,433.00,food_items,0,NaN
9,32,96,239289,12.50,0.80,52,0.0,125,g,125.00,food_items,0,NaN

In [67]:
fake = Faker()

In [68]:
ingredient_id=[]
recipe_id=[]
food_item_id=[]
carbohydrate=[]
protein=[]
energy=[]
lipid_fat=[]
quantity=[]
unit=[]
eqv=[]
food_type=[]
substitute_item_id=[]
substitute_type=[]

In [69]:
for i in range(100000,100100):
  ingredient_id.append("IN"+str(i))
    
for i in range(100000,100100):
  recipe_id.append("RP"+str(i))
    
for i in range(100000,100100):
    food_item_id.append('FI' + str(i))
    
for _ in range(100):
  nos = random.randint(150, 250)
  energy.append(str(nos))

for _ in range(100):
  idnumber = random.randint(100000, 100050)
  substitute_item_id.append("SI"+str(idnumber))

for _ in range(100):
  nos = random.randint(10, 50)
  carbohydrate.append(str(nos))

for _ in range(100):
  nos = random.randint(10, 50)
  protein.append(str(nos))

for _ in range(100):
  nos = random.randint(5, 10)
  lipid_fat.append(str(nos))

for _ in range(100):
  nos = random.randint(7, 450)
  eqv.append(str(nos))
    
for _ in range(100):
  ssize = random.choice([
    "200",
    "150",
    "160",
    "110",
    "130",
    "220",
    "210",
])
  quantity.append(ssize)

for _ in range(100):
  iunit = random.choice([
    "ml",
    "gm",

])
  unit.append(iunit)

for i in range(100):
  food_type.append('recipe')

for i in range(100):
  substitute_type.append(None)

In [70]:
ingredient_dict = {
  'ingredient_id':ingredient_id,
  'recipe_id': recipe_id,
  'food_item_id': food_item_id,
  'carbohydrate': carbohydrate,
  'protein': protein,
  'energy': energy,
  'lipid_fat': lipid_fat,
  'quantity': quantity,
  'unit': unit,
  'eqv': eqv,
  'food_type': food_type,
  'substitute_item_id': substitute_item_id,
  'substitute_type': substitute_type,
}

In [71]:
for key, value in ingredient_dict.items():
    print(f'Key: {key}, Value: {len(value)}')

Key: ingredient_id, Value: 100
Key: recipe_id, Value: 100
Key: food_item_id, Value: 100
Key: carbohydrate, Value: 100
Key: protein, Value: 100
Key: energy, Value: 100
Key: lipid_fat, Value: 100
Key: quantity, Value: 100
Key: unit, Value: 100
Key: eqv, Value: 100
Key: food_type, Value: 100
Key: substitute_item_id, Value: 100
Key: substitute_type, Value: 100

In [72]:
ingredient_df = pd.DataFrame(ingredient_dict)

In [73]:
ingredient_df.head()

,ingredient_id,recipe_id,food_item_id,carbohydrate,protein,energy,lipid_fat,quantity,unit,eqv,food_type,substitute_item_id,substitute_type
0,IN100000,RP100000,FI100000,46,49,156,10,200,ml,340,recipe,SI100020,None
1,IN100001,RP100001,FI100001,36,10,221,6,110,gm,320,recipe,SI100041,None
2,IN100002,RP100002,FI100002,41,24,166,9,150,gm,404,recipe,SI100046,None
3,IN100003,RP100003,FI100003,17,21,151,8,110,ml,319,recipe,SI100006,None
4,IN100004,RP100004,FI100004,30,11,250,7,110,ml,388,recipe,SI100007,None

In [74]:
ingredient_df.to_csv('datasets/Fake_datasets/hca_recipe_ingredients.csv', index=False)